### ISSUE TITLE
Add API v2 docs

### ISSUE THREAD

**Issue by slafleche** [vanilla/docs#126]
Add API v2 docs from vanilla into the public docs. The json file will be static and need to be updated in the docs to get the latest data.

**Comment by tburry** [comment]
- It should be in location /apiv2/api-reference
- It will be similar to the [Swagger UI](https://github.com/vanilla/internal/tree/master/plugins/swagger) plugin and you can use its code as a basis.
- Here is a [generated swagger spec](https://github.com/vanilla/docs/files/1340549/vanilla-apiv2.txt) for the docs.

**Comment by slafleche** [comment]
The Swagger docs are live
