### ISSUE TITLE
Update Swagger Docs

### ISSUE THREAD

**Issue by Charrondev** [vanilla/docs#179]
With the release coming we need to update the swagger docs page. I would be nice to add to to the README the actual process of doing this as well.

**Comment by slafleche** [comment]
To update the swagger docs, you need to update the `/static/js/swagger/swagger-data.json` file. I don't know what we should and shouldn't update, so I'm not the right person to do this task.

**Comment by Charrondev** [comment]
So the process is for right now,

- Open a local vanilla instance
- Enable the Api v2 addon (swagger)
- Enable the groups application
- Hit `/api/v2/swagger`
- Copy/paste the json into the docs `static/js/swagger-data.json`
- Change the `host` key to `example.com`
