### ISSUE TITLE
Help: Posting / Smart Embed

### ISSUE THREAD

**Issue by kaecyra** [vanilla/docs#20]
This section should discuss and explain our automatic embedding of various popular site links such as YouTube, Vimeo, Twitter, etc.

Current:
https://blog.vanillaforums.com/features/automatic-embeds-twitter-instagram-pinterest-youtube-vimeo/
https://blog.vanillaforums.com/help/vanilla-soundcloud-embed/
https://blog.vanillaforums.com/features/embed-your-wistia-videos-in-vanilla/#more-8822

**Comment by LauraMakesArt** [comment]
closed by https://github.com/vanilla/docs/pull/53
