### ISSUE TITLE
Improve Theme hook documentation

### ISSUE THREAD

**Issue by slafleche** [vanilla/docs#201]
https://docs.vanillaforums.com/developer/addons/events-and-handlers/

We should put some real examples in there for common use cases. I'd like to see:

- [x] A concrete and functional example of a theme hooks file for a theme
- [x] Show a few common theme hooks, especially `base_render_before`
- [x] Encouraging users to use theme hooks and not view overwrites (link from view overwrites back to theme hooks page)
- [x] Adding some data to `$sender`. It's important to be clear here that you can add what you want and offer a few different examples
- [x] Some mention or a link to other page with information about using `{debug}` to see and debug data being passed to view.
- [x] Links to smarty page(s)

I dislike using the wording "magic" and having abstract examples with names like "kaboom". Docs should be concrete and offer practical examples.

**Comment by igraziatto** [comment]
It would also be a good idea to cover the "structure" and the "setup" functions.

**Comment by slafleche** [comment]
@igraziatto good idea. Might be a good idea to have a generic page and maybe a page specific to how we do themes with common patterns in theme hooks.

**Comment by slafleche** [comment]
This snippet might be interesting:
https://staff.vanillaforums.com/discussion/182/theming-faq#Comment_635

@Charrondev go over some of your past themes and see if there's anything interesting to pull up as examples. (Remember to put the "This feature is only available on Vanilla Cloud" banner for anything proprietary.
