### ISSUE TITLE
Universal comments page - 404 to wordpress comments link

### ISSUE THREAD

**Issue by Bparm** [vanilla/docs#207]
When you are on the universal comments page https://docs.vanillaforums.com/help/comments/ and want to then access the wordpress comments docs, the hyper link leads to https://docs.vanillaforums.com/help/features/wordpress/using-comments/ but that page is a 404

**Comment by Charrondev** [comment]
Other common 404 links:

- /help/addons/statistics
- /help/ranks
- /help/features/sso/jsconnect/
- /help/addons/reactions/
- /framework/views
- /framework/controllers
- /developer/framework/apiv2/api-endpoints/resource-routing
