### ISSUE TITLE
Code blocks issues

### ISSUE THREAD

**Issue by slafleche** [vanilla/docs#209]
https://docs.vanillaforums.com/developer/framework/modules/

Code needs to scroll horizontally if it's too long. I thought we had this working, so it's either a regression bug, or the source code is incorrect.

They are also weird looking since the scroll axis are always showing:

![screen shot 2018-02-02 at 3 41 27 pm](https://user-images.githubusercontent.com/2412909/35754138-57907ca6-0830-11e8-8047-408936a0d57d.png)

**Comment by Charrondev** [comment]
It's probably a doc full of html tags instead of markdown. We have wrapper for blocks like

```html
<pre>
<code></code>
</pre>
```

But this block is probably just and `<code />` block.
