### ISSUE TITLE
Add documentation on category following and updating your theme

### ISSUE THREAD

**Issue by tburry** [vanilla/docs#210]
We need a description of what category following does and how to enable it and use it. There should also be a section on fixing themes that don't work with it (avoid using the word "old" though).

Once this is written the [toggle description](https://github.com/vanilla/vanilla/pull/6467/files#diff-cf03a5c48f9c9f763cd2eda2de612d82R814) can add a link.

**Comment by slafleche** [comment]
https://github.com/vanilla/docs/pull/216
