### ISSUE TITLE
Please Update Universal Comments

### ISSUE THREAD

**Issue by FarhanVanilla** [vanilla/docs#332]
https://docs.vanillaforums.com/help/comments/#how-to-use-universal-comments

These steps are out of date. I've been telling a bunch of clients to use this feature but these steps make no sense.

**Comment by adrianspeyer** [comment]
These instructions have not changed - although the the screenshots may need a spruce up. Let’s review what’s not clear and make appropriate modifications.

**Comment by nervoustwit** [comment]
I have extensively over-hauled the Universal comments since this issue was made.
https://success.vanillaforums.com/kb/articles/49-universal-comments#troubleshooting
