### ISSUE TITLE
Example-plugin > "Addon not found. The addon you were looking for could not be found."

### ISSUE THREAD

**Issue by Kaspar-K** [vanilla/docs#346]
On
https://docs.vanillaforums.com/developer/addons/addon-quickstart/

"Download the official Example addon."
+
"Ready to code? Grab the Example addon and use it below for an even quicker start. Hang onto your butts, here we go:"

'Example addon' is linking to https://open.vanillaforums.com/addon/example-plugin which return "Addon not found. The addon you were looking for could not be found."

**Comment by tburry** [comment]
Do you know where the example went @linc?

**Comment by linc** [comment]
We removed the example because it was very outdated in its coding practices. Docs should be updated instead.
