### ISSUE TITLE
Facebook Connect publish_actions permission

### ISSUE THREAD

**Issue by petrsvihlik** [vanilla/docs#49]
The [documentation page for FB Connect](http://docs.vanillaforums.com/help/addons/social/facebook/) should contain information on how to fill in the FB App review form. It's not clear which actions in VanillaForums require the permission -> not clear what to fill in the review form. See the following:

> publish_actions is only for custom-built sharing experiences. If your app triggers a Facebook dialog to share, you won't be approved for publish_actions

I tried to disable "social share" and "social reactions" in the FB Connect add-on in Vanilla but the login url contains `scope=email,publish_actions` no matter what I set.

The review form:
![fb_review](https://cloud.githubusercontent.com/assets/9810625/21811989/d782af94-d751-11e6-91c6-07d66eeedc50.png)

**Comment by JanLenoch** [comment]
As of April 27th, it seems that there is still one issue remaining. As mentioned in the screenshot inserted by @petrsvihlik, neither the 'Feed Dialog' nor the 'Share Dialog' can be used by the app to publish, if the 'publish_actions' OAuth scope is requested by the app. Apparently, FB Connect still uses the 'Share Dialog':

![image](https://cloud.githubusercontent.com/assets/17413329/25474822/e034fc5a-2b34-11e7-95ea-8fa86230edf4.png)

(Sorry for the Czech captions.)

It seems that either the scope or the form of sharing (the dialog) still has to be changed to make it possible to submit for review.

**Comment by DaazKu** [comment]
We are removing the publish_actions from our plugin.
