### ISSUE TITLE
Click targets on side menus should be larger

### ISSUE THREAD

**Issue by tburry** [vanilla/docs#58]
In the side menus only the text is clickable to navigate. I should be able to click the padding around the text and the expand/collapse arrows. Nothing should change visually. Just make the padding on the anchors bigger and the padding on the list items smaller. Probably some miscellaneous CSS foozbamery.

<img width="317" alt="vanilla_forums_documentation" src="https://cloud.githubusercontent.com/assets/97432/23321531/f25f81c8-faad-11e6-93c3-15a6a7fd1cb7.png">

**Comment by slafleche** [comment]
In PR: https://github.com/vanilla/docs/pull/79
