### ISSUE TITLE
SSL is not properly configured for docs.vanillaforums.com

### ISSUE THREAD

**Issue by Charrondev** [vanilla/docs#64]
The link [https://docs.vanillaforums.com](https://docs.vanillaforums.com) doesn't seem to work properly. I'm guessing the SSL certificate is not configured correctly. Example:
![screenshot 2017-03-06 17 49 28](https://cloud.githubusercontent.com/assets/1770056/23633948/d2acd9da-0295-11e7-8396-1941451f04a5.png)

Easy fix is to change the link to `http://`. Better solution is to enable https on the docs site.

**Comment by kaecyra** [comment]
I've adjusted to the link to http. The docs are hosted on GitHub and its not possible to host them with an SSL cert.
